import { DefaultTheme } from "styled-components"

export const theme: DefaultTheme = {
  colors: {
    black: "#000000",
    white: "#FFFFFF",
    moon: "#edddb3",
    charcoal: "#353239",
    brown: "#54433a",
    hoverText: "#B2AB99",
    moonDark: "#E3CB8A",
    moonComplementary: "#B3C3ED",
    html: "#E44D26",
    css: "#1572B6",
    javascript: "#F0DB4F",
    rubyonrails: "#A62C39",
    react: "#61DAFB",
    chelsea: "#02ac91",
    aws: "#F7A80D",
    typescript: "#007acc",
    python: "",
    postgresql: "",
    java: "#EA2D2E",
    git: "",
    firebase: "",
    lightPurple: "#c9b3ed",
    purple: "#8c7da6",
    limeGreen: "#dcedb3",
    teaGreen: "#9aa67d",
  },
}
